version: '3'
services:
    php-apache:
        image: ecomueble:php_apache
        ports:
            - 80:80
        volumes:
            - ./app:/var/www/html
        links:
            - 'mariadb'

    mariadb:
        image: ecomueble:mariadb_server
        ports:
            - 3306:3306
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "wilson"
            

volumes:
    mariadb:
